/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'emoji' : IDL.Text,
  'pricePerCap' : IDL.Nat,
});
export const Order = IDL.Record({
  'user' : IDL.Principal,
  'productId' : IDL.Nat,
  'orderId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'totalPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'emoji' : IDL.Text,
    'pricePerCap' : IDL.Nat,
  });
  const Order = IDL.Record({
    'user' : IDL.Principal,
    'productId' : IDL.Nat,
    'orderId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'totalPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };